// MEE 世界：一個行得走得嘅小鎮，唔係一個細框。
//
// Two things make this feel like a place rather than a widget, and both are
// deliberate:
//
// 1. The map is much bigger than the screen and the camera follows the child.
//    An earlier version fitted a whole zone into one viewport, which meant
//    two steps in any direction hit the edge — 行兩步就撞埋. Zooming the map
//    past the viewport is what buys real walking distance.
//
// 2. Where you can walk comes from the art itself (src/lib/walkmask.ts,
//    generated by scripts/build-walkmask.mjs), not from a rectangle. The
//    child follows the actual stone paths and cannot stand on a roof or in
//    the sea, which is most of what sells a top-down world.
//
// Night is the same map graded darker (scripts/make-night.mjs) rather than
// separate art. The night art that came with the set is drawn from street
// level while these maps are top-down, so using it would move the ground
// under the child every evening and need every door placed twice.
//
// All positions are normalised 0-1 over the map image, so replacing a
// background at a different resolution changes nothing here.

import { WALK_MASKS, type WalkMask } from "./walkmask";

// A board is neither a room nor a zone — it opens a panel in place. 小鎮趣聞
// and 最新消息 live behind one, and they are kept apart there: a parent who
// cannot tell a made-up pet story from a real announcement stops trusting
// both.
export type HotspotKind = "door" | "gate" | "board" | "stall";

export interface Hotspot {
  id: string;
  kind: HotspotKind;
  label: string;
  /** Normalised position on the map, standing on the path at the entrance. */
  x: number;
  y: number;
  /** A room id for a door, a zone id for a gate. */
  target: string;
}

export interface Zone {
  id: string;
  name: string;
  /** The same place at different times; all three share one walk mask. */
  day: string;
  night: string;
  /** Only 小屋區入口 has dawn art; everywhere else goes straight day/night. */
  dawn?: string;
  /** 碼頭市集 is the parents' entrance and asks for the parent PIN. */
  parentsOnly?: boolean;
  /** Key into WALK_MASKS — shared by day and night. */
  mask: string;
  /**
   * Where the child stands on arriving. Deliberately set back from the return
   * gate: spawning on it put "返小鎮" under their thumb the moment they got
   * here, so the first tap sent them straight home again.
   */
  spawn: { x: number; y: number };
  hotspots: Hotspot[];
}

export const ZONES: Record<string, Zone> = {
  // 小鎮中心 — the hub. Three doors (Buddy Café, Hero Studio, MEE 珍藏館) and
  // two gates (碼頭市集, 小鎮廣場), which is exactly what the signpost in the
  // art promises.
  "town-centre": {
    id: "town-centre",
    name: "小鎮中心",
    day: "/assets/world/town-centre-day.webp",
    night: "/assets/world/town-centre-night.webp",
    mask: "town-centre",
    spawn: { x: 0.450, y: 0.880 },
    hotspots: [
      { id: "d-cafe", kind: "door", label: "Buddy Café", x: 0.330, y: 0.260, target: "cafe" },
      { id: "d-studio", kind: "door", label: "Hero Studio", x: 0.800, y: 0.420, target: "studio" },
      { id: "d-album-hall", kind: "door", label: "MEE 珍藏館", x: 0.680, y: 0.680, target: "album-hall" },
      { id: "g-wharf", kind: "gate", label: "碼頭市集", x: 0.790, y: 0.930, target: "wharf-market" },
      { id: "g-square", kind: "gate", label: "小鎮廣場", x: 0.460, y: 0.980, target: "town-square" },
    ],
  },

  // 小鎮廣場 — where the pets gather, and where the notice board lives.
  "town-square": {
    id: "town-square",
    name: "小鎮廣場",
    day: "/assets/world/town-square-day.webp",
    night: "/assets/world/town-square-night.webp",
    mask: "town-square",
    spawn: { x: 0.440, y: 0.800 },
    hotspots: [
      { id: "b-board", kind: "board", label: "公告板", x: 0.460, y: 0.470, target: "notice-board" },
      { id: "g-centre", kind: "gate", label: "小鎮中心", x: 0.450, y: 0.980, target: "town-centre" },
      { id: "g-park", kind: "gate", label: "散步公園", x: 0.070, y: 0.680, target: "seaside-park" },
      { id: "g-village", kind: "gate", label: "小屋區入口", x: 0.860, y: 0.420, target: "village-gate" },
    ],
  },

  // 散步公園 — a seaside walk. Two gates and nothing to enter: the point of
  // it is the walk itself and the pets who like it here.
  "seaside-park": {
    id: "seaside-park",
    name: "散步公園",
    day: "/assets/world/seaside-park-day.webp",
    night: "/assets/world/seaside-park-night.webp",
    mask: "seaside-park",
    spawn: { x: 0.460, y: 0.870 },
    hotspots: [
      { id: "g-square", kind: "gate", label: "小鎮廣場", x: 0.420, y: 0.980, target: "town-square" },
      { id: "g-village", kind: "gate", label: "小屋區入口", x: 0.780, y: 0.280, target: "village-gate" },
    ],
  },

  // 小屋區入口 — the child's own front door, and the only zone with a dawn
  // variant.
  "village-gate": {
    id: "village-gate",
    name: "小屋區入口",
    day: "/assets/world/village-gate-day.webp",
    night: "/assets/world/village-gate-night.webp",
    dawn: "/assets/world/village-gate-dawn.webp",
    mask: "village-gate",
    spawn: { x: 0.420, y: 0.850 },
    hotspots: [
      { id: "d-home", kind: "door", label: "我的小屋", x: 0.180, y: 0.630, target: "my-home" },
      { id: "g-square", kind: "gate", label: "小鎮廣場", x: 0.440, y: 0.980, target: "town-square" },
      { id: "g-park", kind: "gate", label: "散步公園", x: 0.845, y: 0.355, target: "seaside-park" },
    ],
  },

  // 碼頭市集 — the parents' entrance. The船飛 is the existing parent PIN; the
  // gate itself is in the world so a child can see the place exists and be
  // told, gently, that it is for grown-ups.
  "wharf-market": {
    id: "wharf-market",
    name: "碼頭市集",
    day: "/assets/world/wharf-market-day.webp",
    night: "/assets/world/wharf-market-night.webp",
    mask: "wharf-market",
    parentsOnly: true,
    spawn: { x: 0.470, y: 0.850 },
    hotspots: [
      { id: "g-centre", kind: "gate", label: "小鎮中心", x: 0.470, y: 0.980, target: "town-centre" },
      // The five counters Em labelled on the annotated map. Each opens a page
      // that already exists — the market is a way in, not a new set of
      // screens for the same jobs.
      { id: "s-card-desk", kind: "stall", label: "管理自我介紹卡", x: 0.260, y: 0.600, target: "card-desk" },
      { id: "s-new-child", kind: "stall", label: "新增孩子檔案", x: 0.470, y: 0.500, target: "new-child" },
      { id: "s-harbour", kind: "stall", label: "付款訂閱", x: 0.680, y: 0.600, target: "harbour" },
      { id: "s-lost", kind: "stall", label: "認領失物區", x: 0.720, y: 0.630, target: "lost" },
      { id: "s-security", kind: "stall", label: "保安", x: 0.470, y: 0.720, target: "security" },
    ],
  },
};

export const START_ZONE = "town-centre";


/** Interior art, used by the page a door leads into. */
export const ROOM_ART: Record<string, string> = {
  "cafe": "/assets/world/cafe.webp",
  "studio": "/assets/world/studio.webp",
  "album-hall": "/assets/world/album-hall.webp",
  "album-books": "/assets/world/album-books.webp",
  "fragment-room": "/assets/world/fragment-room.webp",
  "library": "/assets/world/library.webp",
  "cinema-lobby": "/assets/world/cinema-lobby.webp",
  "cinema-hall": "/assets/world/cinema-hall.webp",
  "my-home": "/assets/world/my-home.webp",
};

/**
 * Rooms reached from inside another room rather than from a zone: the
 * 珍藏館's two wings, and the 戲院 behind its lobby. Each says which room it
 * came from so the return door knows where to send the child back to, which
 * is the whole of Em's "原位入口原位出口" rule for interiors.
 */
export const ROOM_DOORS: Record<string, Array<{ id: string; label: string; target: string; side: "left" | "right" }>> = {
  "album-hall": [
    { id: "r-books", label: "卡冊珍藏館", target: "album-books", side: "right" },
    { id: "r-fragments", label: "碎片拼合室", target: "fragment-room", side: "left" },
  ],
  "studio": [
    { id: "r-library", label: "圖書館", target: "library", side: "right" },
    { id: "r-cinema", label: "戲院大堂", target: "cinema-lobby", side: "left" },
  ],
  "cinema-lobby": [
    { id: "r-hall", label: "入場", target: "cinema-hall", side: "right" },
  ],
};

/** The room a return door leads back to, derived from ROOM_DOORS. */
export const ROOM_PARENT: Record<string, string> = Object.fromEntries(
  Object.entries(ROOM_DOORS).flatMap(([parent, doors]) =>
    doors.map(door => [door.target, parent])),
);

/** Which zone a room lives in, so a deep link can put the child back outside it. */
export const ROOM_ZONE: Record<string, string> = Object.fromEntries(
  Object.values(ZONES).flatMap(zone =>
    zone.hotspots.filter(spot => spot.kind === "door").map(spot => [spot.target, zone.id])),
);

/**
 * Which half of the day it is. The world follows the child's own clock rather
 * than a setting, so evening play looks like evening.
 */
export function isDaytime(now: Date = new Date()): boolean {
  const hour = now.getHours();
  return hour >= 6 && hour < 18;
}

/**
 * Dawn, for the one zone that has art for it. A narrow window on purpose:
 * 小屋區入口 is where the child's own house is, so catching it at first light
 * should feel like catching it, not like a third of the day.
 */
export function isDawn(now: Date = new Date()): boolean {
  const hour = now.getHours();
  return hour >= 5 && hour < 7;
}

export function zoneBackground(zone: Zone, now?: Date): string {
  if (zone.dawn && isDawn(now)) return zone.dawn;
  return isDaytime(now) ? zone.day : zone.night;
}

// ---------------------------------------------------------------------------
// Walkability
// ---------------------------------------------------------------------------

const decoded = new Map<string, Uint8Array>();

function bitsFor(mask: WalkMask): Uint8Array {
  const cached = decoded.get(mask.bits);
  if (cached) return cached;
  const binary = atob(mask.bits);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  decoded.set(mask.bits, bytes);
  return bytes;
}

export function maskFor(zone: Zone): WalkMask | null {
  return WALK_MASKS[zone.mask] ?? null;
}

/** Aspect ratio of a zone's map, needed to size the scrolling canvas. */
export function zoneAspect(zone: Zone): number {
  const mask = maskFor(zone);
  return mask ? mask.imageWidth / mask.imageHeight : 941 / 1672;
}

export function isWalkable(zone: Zone, x: number, y: number): boolean {
  const mask = maskFor(zone);
  if (!mask) return true;
  if (x < 0 || y < 0 || x > 1 || y > 1) return false;
  const cx = Math.min(mask.width - 1, Math.floor(x * mask.width));
  const cy = Math.min(mask.height - 1, Math.floor(y * mask.height));
  const index = cy * mask.width + cx;
  return ((bitsFor(mask)[index >> 3] >> (index & 7)) & 1) === 1;
}

/**
 * Nearest walkable point to an arbitrary one. Tapping a rooftop should walk
 * the child to the doorstep in front of it rather than doing nothing, which
 * is the difference between a world that feels responsive and one that feels
 * broken.
 */
export function nearestWalkable(zone: Zone, x: number, y: number): { x: number; y: number } | null {
  if (isWalkable(zone, x, y)) return { x, y };
  const mask = maskFor(zone);
  if (!mask) return { x, y };
  const bytes = bitsFor(mask);
  let best: { x: number; y: number } | null = null;
  let bestDistance = Infinity;
  for (let cy = 0; cy < mask.height; cy++) {
    for (let cx = 0; cx < mask.width; cx++) {
      const index = cy * mask.width + cx;
      if (((bytes[index >> 3] >> (index & 7)) & 1) === 0) continue;
      const nx = (cx + 0.5) / mask.width;
      const ny = (cy + 0.5) / mask.height;
      const distance = Math.hypot(nx - x, ny - y);
      if (distance < bestDistance) { bestDistance = distance; best = { x: nx, y: ny }; }
    }
  }
  return best;
}

/**
 * Where the child stands on arriving from somewhere specific — the gate they
 * came through, or the door of the room they just left.
 *
 * Arriving always used the zone's fixed spawn, so walking to the 碼頭 and back
 * dropped the child at the town's roundabout instead of at the 碼頭 gate they
 * had just stepped out of. A world loses its shape fast if leaving a place
 * does not put you back outside it.
 *
 * The landing point is nudged away from the entrance so its own prompt is not
 * already under the child's thumb, which would send them straight back.
 */
export function arrivalPoint(zone: Zone, from?: { zone?: string; room?: string } | null): { x: number; y: number } {
  const entrance = from?.room
    ? zone.hotspots.find(spot => spot.kind === "door" && spot.target === from.room)
    : from?.zone
      ? zone.hotspots.find(spot => spot.kind === "gate" && spot.target === from.zone)
      : null;
  if (!entrance) return zone.spawn;
  return stepAwayFrom(zone, entrance, zone.spawn);
}

/**
 * The closest walkable spot that is out of `at`'s own reach, preferring ones
 * on the `toward` side of it.
 *
 * A straight line toward the middle of the map was the obvious approach and
 * the wrong one: several entrances sit at the mouth of a narrow path, so the
 * line left walkable ground on its first step and the child never got clear
 * of the prompt. Searching the mask always finds standing room if any exists.
 */
function stepAwayFrom(zone: Zone, at: { x: number; y: number }, toward: { x: number; y: number }): { x: number; y: number } {
  const mask = maskFor(zone);
  if (!mask) return at;
  const bytes = bitsFor(mask);
  const clear = REACH * 1.7;
  let best: { x: number; y: number } | null = null;
  let bestCost = Infinity;
  for (let cy = 0; cy < mask.height; cy++) {
    for (let cx = 0; cx < mask.width; cx++) {
      const index = cy * mask.width + cx;
      if (((bytes[index >> 3] >> (index & 7)) & 1) === 0) continue;
      const nx = (cx + 0.5) / mask.width;
      const ny = (cy + 0.5) / mask.height;
      // Measured the same way hotspotNear measures, or the child could land
      // just inside the prompt they were meant to step out of.
      if (Math.hypot(nx - at.x, (ny - at.y) * 0.6) <= clear) continue;
      const away = Math.hypot(nx - at.x, ny - at.y);
      const inward = Math.hypot(nx - toward.x, ny - toward.y);
      // Close to the entrance, and on the side facing the rest of the map.
      const cost = away + inward * 0.25;
      if (cost < bestCost) { bestCost = cost; best = { x: nx, y: ny }; }
    }
  }
  return best ?? at;
}

/** Close enough to a hotspot for its prompt to appear. */
export const REACH = 0.055;

export function hotspotNear(zone: Zone, x: number, y: number): Hotspot | null {
  let best: Hotspot | null = null;
  let bestDistance = REACH;
  for (const spot of zone.hotspots) {
    // The maps are tall, so a plain distance would let the child trigger a
    // door from much further up or down the street than sideways.
    const distance = Math.hypot(spot.x - x, (spot.y - y) * 0.6);
    if (distance < bestDistance) { best = spot; bestDistance = distance; }
  }
  return best;
}
