// MEE 世界：一個行得走得嘅小鎮，唔係一個細框。
//
// Two things make this feel like a place rather than a widget, and both are
// deliberate:
//
// 1. The map is much bigger than the screen and the camera follows the child.
//    An earlier version fitted a whole zone into one viewport, which meant
//    two steps in any direction hit the edge — 行兩步就撞埋. Zooming the map
//    past the viewport is what buys real walking distance.
//
// 2. Where you can walk comes from the art itself (src/lib/walkmask.ts,
//    generated by scripts/build-walkmask.mjs), not from a rectangle. The
//    child follows the actual stone paths and cannot stand on a roof or in
//    the sea, which is most of what sells a top-down world.
//
// Night is the same map graded darker (scripts/make-night.mjs) rather than
// separate art. The night art that came with the set is drawn from street
// level while these maps are top-down, so using it would move the ground
// under the child every evening and need every door placed twice.
//
// All positions are normalised 0-1 over the map image, so replacing a
// background at a different resolution changes nothing here.

import { WALK_MASKS, type WalkMask } from "./walkmask";

export type HotspotKind = "door" | "gate";

export interface Hotspot {
  id: string;
  kind: HotspotKind;
  label: string;
  /** Normalised position on the map, standing on the path at the entrance. */
  x: number;
  y: number;
  /** A room id for a door, a zone id for a gate. */
  target: string;
}

export interface Zone {
  id: string;
  name: string;
  /** Both are the same map; the night one is a graded copy. */
  day: string;
  night: string;
  /** Key into WALK_MASKS — shared by day and night. */
  mask: string;
  /**
   * Where the child stands on arriving. Deliberately set back from the return
   * gate: spawning on it put "返小鎮" under their thumb the moment they got
   * here, so the first tap sent them straight home again.
   */
  spawn: { x: number; y: number };
  hotspots: Hotspot[];
}

export const ZONES: Record<string, Zone> = {
  town: {
    id: "town",
    name: "MEE 小鎮",
    day: "/assets/town-morning-v2.webp",
    night: "/assets/town-morning-v2-night.webp",
    mask: "town-morning-v2",
    spawn: { x: 0.500, y: 0.820 },
    hotspots: [
      { id: "d-library", kind: "door", label: "MEE 圖書館", x: 0.766, y: 0.473, target: "library" },
      { id: "d-cinema", kind: "door", label: "MEE 戲院", x: 0.266, y: 0.705, target: "cinema" },
      { id: "d-cafe", kind: "door", label: "Paw Café", x: 0.238, y: 0.497, target: "cafe" },
      { id: "d-studio", kind: "door", label: "Hero Studio", x: 0.495, y: 0.488, target: "studio" },
      { id: "d-petroom", kind: "door", label: "寵物房", x: 0.328, y: 0.307, target: "petroom" },
      { id: "g-dock", kind: "gate", label: "去碼頭", x: 0.850, y: 0.260, target: "dock" },
      { id: "g-fair", kind: "gate", label: "去嘉年華", x: 0.500, y: 0.960, target: "fair" },
      { id: "g-village", kind: "gate", label: "去蘑菇村", x: 0.224, y: 0.909, target: "village" },
    ],
  },
  dock: {
    id: "dock",
    name: "碼頭",
    day: "/assets/dock-town-dusk.webp",
    night: "/assets/dock-town-dusk-night.webp",
    mask: "dock-town-dusk",
    spawn: { x: 0.495, y: 0.720 },
    hotspots: [
      { id: "d-market", kind: "door", label: "碼頭市集", x: 0.224, y: 0.640, target: "market" },
      { id: "g-town", kind: "gate", label: "返小鎮", x: 0.495, y: 0.833, target: "town" },
    ],
  },
  // Named 嘉年華 rather than 遊樂場 because 遊樂場 is one of the rooms inside
  // it — a zone and a room sharing a name would read as a loop on the signs.
  fair: {
    id: "fair",
    name: "嘉年華",
    day: "/assets/amusement-park.webp",
    night: "/assets/amusement-park-night.webp",
    mask: "amusement-park",
    spawn: { x: 0.464, y: 0.780 },
    hotspots: [
      { id: "d-theater", kind: "door", label: "劇院", x: 0.786, y: 0.430, target: "theater" },
      { id: "d-park", kind: "door", label: "遊樂場", x: 0.280, y: 0.500, target: "park" },
      { id: "g-town", kind: "gate", label: "返小鎮", x: 0.464, y: 0.900, target: "town" },
    ],
  },
  village: {
    id: "village",
    name: "蘑菇村",
    day: "/assets/mushroom-city-morning.webp",
    night: "/assets/mushroom-city-morning-night.webp",
    mask: "mushroom-city-morning",
    spawn: { x: 0.500, y: 0.850 },
    hotspots: [
      { id: "d-album", kind: "door", label: "MEE 收藏館", x: 0.828, y: 0.371, target: "album" },
      { id: "g-town", kind: "gate", label: "返小鎮", x: 0.500, y: 0.960, target: "town" },
    ],
  },
};

export const START_ZONE = "town";

/** Interior art, used by the page a door leads into. */
export const ROOM_ART: Record<string, string> = {
  library: "/assets/mee-library.webp",
  cinema: "/assets/mee-cinema.webp",
  cafe: "/assets/paw-cafe.webp",
  market: "/assets/wharf-market-morning.webp",
  studio: "/assets/hero-studio.webp",
  theater: "/assets/theater.webp",
  park: "/assets/amusement-park.webp",
  petroom: "/assets/pet-room.webp",
  album: "/assets/mee-album-house.webp",
};

/** Which zone a room lives in, so a deep link can put the child back outside it. */
export const ROOM_ZONE: Record<string, string> = Object.fromEntries(
  Object.values(ZONES).flatMap(zone =>
    zone.hotspots.filter(spot => spot.kind === "door").map(spot => [spot.target, zone.id])),
);

/**
 * Which half of the day it is. The world follows the child's own clock rather
 * than a setting, so evening play looks like evening.
 */
export function isDaytime(now: Date = new Date()): boolean {
  const hour = now.getHours();
  return hour >= 6 && hour < 18;
}

export function zoneBackground(zone: Zone, now?: Date): string {
  return isDaytime(now) ? zone.day : zone.night;
}

// ---------------------------------------------------------------------------
// Walkability
// ---------------------------------------------------------------------------

const decoded = new Map<string, Uint8Array>();

function bitsFor(mask: WalkMask): Uint8Array {
  const cached = decoded.get(mask.bits);
  if (cached) return cached;
  const binary = atob(mask.bits);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  decoded.set(mask.bits, bytes);
  return bytes;
}

export function maskFor(zone: Zone): WalkMask | null {
  return WALK_MASKS[zone.mask] ?? null;
}

/** Aspect ratio of a zone's map, needed to size the scrolling canvas. */
export function zoneAspect(zone: Zone): number {
  const mask = maskFor(zone);
  return mask ? mask.imageWidth / mask.imageHeight : 941 / 1672;
}

export function isWalkable(zone: Zone, x: number, y: number): boolean {
  const mask = maskFor(zone);
  if (!mask) return true;
  if (x < 0 || y < 0 || x > 1 || y > 1) return false;
  const cx = Math.min(mask.width - 1, Math.floor(x * mask.width));
  const cy = Math.min(mask.height - 1, Math.floor(y * mask.height));
  const index = cy * mask.width + cx;
  return ((bitsFor(mask)[index >> 3] >> (index & 7)) & 1) === 1;
}

/**
 * Nearest walkable point to an arbitrary one. Tapping a rooftop should walk
 * the child to the doorstep in front of it rather than doing nothing, which
 * is the difference between a world that feels responsive and one that feels
 * broken.
 */
export function nearestWalkable(zone: Zone, x: number, y: number): { x: number; y: number } | null {
  if (isWalkable(zone, x, y)) return { x, y };
  const mask = maskFor(zone);
  if (!mask) return { x, y };
  const bytes = bitsFor(mask);
  let best: { x: number; y: number } | null = null;
  let bestDistance = Infinity;
  for (let cy = 0; cy < mask.height; cy++) {
    for (let cx = 0; cx < mask.width; cx++) {
      const index = cy * mask.width + cx;
      if (((bytes[index >> 3] >> (index & 7)) & 1) === 0) continue;
      const nx = (cx + 0.5) / mask.width;
      const ny = (cy + 0.5) / mask.height;
      const distance = Math.hypot(nx - x, ny - y);
      if (distance < bestDistance) { bestDistance = distance; best = { x: nx, y: ny }; }
    }
  }
  return best;
}

/** Close enough to a hotspot for its prompt to appear. */
export const REACH = 0.055;

export function hotspotNear(zone: Zone, x: number, y: number): Hotspot | null {
  let best: Hotspot | null = null;
  let bestDistance = REACH;
  for (const spot of zone.hotspots) {
    // The maps are tall, so a plain distance would let the child trigger a
    // door from much further up or down the street than sideways.
    const distance = Math.hypot(spot.x - x, (spot.y - y) * 0.6);
    if (distance < bestDistance) { best = spot; bestDistance = distance; }
  }
  return best;
}
