// MEE 世界：一個行得走得嘅小鎮，唔係一個細框。
//
// Two things make this feel like a place rather than a widget, and both are
// deliberate:
//
// 1. The map is much bigger than the screen and the camera follows the child.
//    An earlier version fitted a whole zone into one viewport, which meant
//    two steps in any direction hit the edge — 行兩步就撞埋. Zooming the map
//    past the viewport is what buys real walking distance.
//
// 2. Where you can walk comes from the art itself (src/lib/walkmask.ts,
//    generated by scripts/build-walkmask.mjs), not from a rectangle. The
//    child follows the actual stone paths and cannot stand on a roof or in
//    the sea, which is most of what sells a top-down world.
//
// Night is the same map graded darker (scripts/make-night.mjs) rather than
// separate art. The night art that came with the set is drawn from street
// level while these maps are top-down, so using it would move the ground
// under the child every evening and need every door placed twice.
//
// All positions are normalised 0-1 over the map image, so replacing a
// background at a different resolution changes nothing here.

import { WALK_MASKS, type WalkMask } from "./walkmask";

// A board is neither a room nor a zone — it opens a panel in place. 小鎮趣聞
// and 最新消息 live behind one, and they are kept apart there: a parent who
// cannot tell a made-up pet story from a real announcement stops trusting
// both.
export type HotspotKind =
  | "door" | "gate" | "board" | "stall" | "stage" | "seat" | "cottage";

export interface Hotspot {
  id: string;
  kind: HotspotKind;
  label: string;
  /** Normalised position on the map, standing on the path at the entrance. */
  x: number;
  y: number;
  /** A room id for a door, a zone id for a gate. */
  target: string;
  /**
   * A line for the things that are not doors: what a child sees sitting on
   * this bench, or why this cottage will not open. Kept on the hotspot rather
   * than in the component so the scene owns its own words.
   */
  note?: string;
}

export interface Zone {
  id: string;
  name: string;
  /** The same place at different times; all three share one walk mask. */
  day: string;
  night: string;
  /**
   * Landscape cuts of the same scene, for a screen wider than it is tall.
   *
   * Em draws both: a 9:16 for a phone and a 16:9 for a desktop. Stretching
   * one to fit the other is what makes a town look like a smear, and
   * letterboxing it breaks the illusion of standing somewhere — so the wide
   * screen gets the wide painting.
   *
   * The catch, and it is the whole reason no zone sets these yet: the
   * hotspots and the walk mask live in the portrait cut's coordinates, so a
   * wide cut only works when it is the *same painting* framed wider — same
   * camera, more left and right, nothing moved or redrawn. The 16:9 files
   * delivered so far are separate renders of the same scene: measured against
   * the portrait, 小屋區入口's paw-print arch sits at y 0.643 in one and
   * 0.574 in the other, and the buildings are at a different scale. Point a
   * zone at one of those and every door marker lands on grass.
   *
   * So the files ship, unwired, and these fields wait for a wide cut that is
   * a crop rather than a re-render.
   */
  dayWide?: string;
  nightWide?: string;
  /** Dawn art, when a scene has a 清晨 cut. Nothing has one right now. */
  dawn?: string;
  /** 碼頭市集 is the parents' entrance and asks for the parent PIN. */
  parentsOnly?: boolean;
  /** Key into WALK_MASKS — shared by day and night. */
  mask: string;
  /**
   * Where the child stands on arriving. Deliberately set back from the return
   * gate: spawning on it put "返小鎮" under their thumb the moment they got
   * here, so the first tap sent them straight home again.
   */
  spawn: { x: number; y: number };
  hotspots: Hotspot[];
}

export const ZONES: Record<string, Zone> = {
  // 小鎮中心 — the hub, and the first thing anybody sees.
  //
  // Read off the art that actually ships. An earlier pass positioned five
  // doors around a compass plaza, from art that was described in chat but
  // never landed as a file — so every marker sat on scenery. This painting
  // has three shopfronts up one climbing stone path, and that is what the
  // hotspots now are.
  //
  // 戲院大堂 and 圖書館 are not on this street. They are reached from inside
  // Hero Studio, which is where Em put their doors.
  "town-centre": {
    id: "town-centre",
    name: "小鎮中心",
    day: "/assets/world/town-centre-day.webp",
    night: "/assets/world/town-centre-night.webp",
    mask: "town-centre",
    // Measured off Em's 2026-08-24 art: a sand plaza with a compass rose,
    // five shopfronts around it, the road out at the bottom and the path to
    // the pier climbing away at the top right.
    //
    // All five shopfronts open. The cinema and the library are also reached
    // through Hero Studio — Em: 「兩邊都得」 — which used to be impossible
    // because an interior carried exactly one `back` target and a second way
    // in would have made the way out lie. The door a child came through now
    // travels with them (see `interiorPath` in interiors.ts), so both are
    // true at once.
    spawn: { x: 0.465, y: 0.800 },
    hotspots: [
      { id: "d-cinema", kind: "door", label: "戲院大堂", x: 0.200, y: 0.355, target: "cinema-lobby" },
      { id: "d-studio", kind: "door", label: "Hero Studio", x: 0.465, y: 0.360, target: "studio" },
      { id: "d-library", kind: "door", label: "MEE 圖書館", x: 0.750, y: 0.375, target: "library" },
      { id: "d-cafe", kind: "door", label: "Buddy Café", x: 0.235, y: 0.605, target: "cafe" },
      { id: "d-album-hall", kind: "door", label: "MEE 珍藏館", x: 0.750, y: 0.655, target: "album-hall" },
      { id: "g-wharf", kind: "gate", label: "碼頭市集", x: 0.885, y: 0.100, target: "wharf-market" },
      { id: "g-square", kind: "gate", label: "小鎮廣場", x: 0.465, y: 0.980, target: "town-square" },
    ],
  },

  // 小鎮廣場 — where the pets gather, and where the notice board lives.
  // Em's stage lives here too, on the raised round platform.
  "town-square": {
    id: "town-square",
    name: "小鎮廣場",
    day: "/assets/world/town-square-day.webp",
    night: "/assets/world/town-square-night.webp",
    mask: "town-square",
    spawn: { x: 0.470, y: 0.800 },
    // Read off the shipped painting: a timber stage under bunting at the top
    // left with steps down onto the plaza, a fountain behind it, the notice
    // board in the middle, a stone arch to 小屋區 on the right, the park
    // signpost on the left, and the road out at the bottom.
    hotspots: [
      // The stage is real now. Em's 2026-08-24 square has a timber deck under
      // a bunting canopy at the top left, with steps down onto the plaza —
      // the marker stands at the foot of those steps.
      { id: "b-stage", kind: "stage", label: "小舞台", x: 0.340, y: 0.345, target: "stage" },
      { id: "b-board", kind: "board", label: "公告板", x: 0.470, y: 0.615, target: "notice-board" },
      { id: "g-village", kind: "gate", label: "小屋區入口", x: 0.845, y: 0.335, target: "village-gate" },
      { id: "g-park", kind: "gate", label: "散步公園", x: 0.055, y: 0.645, target: "seaside-park" },
      { id: "g-centre", kind: "gate", label: "小鎮中心", x: 0.470, y: 0.980, target: "town-centre" },
    ],
  },

  // 散步公園 — a seaside walk. Nothing to enter and nothing to earn: it is
  // the one place in the town that is only for being in.
  //
  // Em's new art (2026-08-16). The path forks around a stream, and the things
  // scattered along it are the point — 「公園長椅及野餐墊是可以有『坐下』嘅
  // 互動」. Five places to sit, each on its own patch of grass off the path,
  // because a bench you have to leave the path for is a bench you chose.
  "seaside-park": {
    id: "seaside-park",
    name: "散步公園",
    day: "/assets/world/seaside-park-day.webp",
    night: "/assets/world/seaside-park-night.webp",
    mask: "seaside-park",
    spawn: { x: 0.490, y: 0.840 },
    hotspots: [
      { id: "s-picnic", kind: "seat", label: "野餐墊", x: 0.220, y: 0.410, target: "picnic",
        note: "坐喺野餐墊上面，籃入面有三文治同果汁。海風吹過嚟，凍凍地好舒服。" },
      { id: "s-bench-mid", kind: "seat", label: "長椅", x: 0.255, y: 0.495, target: "bench-mid",
        note: "坐低，望住條石仔路。有隻蝴蝶停咗喺你隔籬張凳背度。" },
      { id: "s-swing", kind: "seat", label: "鞦韆椅", x: 0.185, y: 0.752, target: "swing",
        note: "鞦韆椅慢慢咁擺。頭頂啲玫瑰花同彩帶跟住風一齊郁。" },
      { id: "s-bench-sea", kind: "seat", label: "海邊長椅", x: 0.585, y: 0.164, target: "bench-sea",
        note: "海就喺石欄後面。遠處有幾隻白色帆船，慢到好似冇郁過咁。" },
      { id: "s-bench-map", kind: "seat", label: "地圖旁長椅", x: 0.720, y: 0.282, target: "bench-map",
        note: "隔籬塊板畫住成個公園嘅地圖。你搵到自己而家坐緊嘅位置。" },
      { id: "g-village", kind: "gate", label: "小屋區入口", x: 0.845, y: 0.045, target: "village-gate" },
      { id: "g-square", kind: "gate", label: "小鎮廣場", x: 0.470, y: 0.980, target: "town-square" },
    ],
  },

  // 小屋區入口 — the child's own front door, behind a paw-print arch.
  //
  // Em's new art (2026-08-16). Six cottages; the big terracotta-roofed one on
  // the left is 我的小屋 and the other five belong to the pets —「其餘係小寵物
  // 的家，不能進入（暫時，有機會遲d開放）」. They are hotspots anyway rather
  // than scenery: a child will tap a front door whether or not it opens, and
  // a tap that says whose house it is reads as a place, while a tap that does
  // nothing reads as broken.
  //
  // The dawn cut is gone. The old one was a different scene entirely (a canal
  // town with a lighthouse), so keeping it would have put these doorways over
  // an unrelated painting for 90 minutes every morning. It comes back the day
  // there is a 清晨 cut of this village.
  "village-gate": {
    id: "village-gate",
    name: "小屋區入口",
    day: "/assets/world/village-gate-day.webp",
    night: "/assets/world/village-gate-night.webp",
    mask: "village-gate",
    spawn: { x: 0.500, y: 0.585 },
    hotspots: [
      // The teal door with a paw print on it, at the foot of the wooden steps.
      // The same paw is carved over the arch, which is what marks this as the
      // child's own house rather than one more cottage.
      { id: "d-home", kind: "door", label: "我的小屋", x: 0.290, y: 0.528, target: "my-home" },
      { id: "c-tower", kind: "cottage", label: "紫色小塔", x: 0.280, y: 0.226, target: "tower",
        note: "紫色屋頂嗰間細細間，門口有粒星。屋主而家唔喺屋企。" },
      { id: "c-shell", kind: "cottage", label: "貝殼小屋", x: 0.535, y: 0.195, target: "shell",
        note: "個屋頂好似隻大貝殼。窗簾拉埋咗，好似瞓緊覺咁。" },
      { id: "c-clock", kind: "cottage", label: "時鐘木屋", x: 0.740, y: 0.195, target: "clock",
        note: "門上面掛住個綠色時鐘。信箱塞住幾封未拆嘅信。" },
      { id: "c-green", kind: "cottage", label: "玻璃花房", x: 0.770, y: 0.358, target: "greenhouse",
        note: "成間屋都係玻璃，入面種滿盆栽，霧氣蒙住睇唔清楚。" },
      { id: "c-blue", kind: "cottage", label: "藍頂小屋", x: 0.820, y: 0.550, target: "blue",
        note: "藍色屋頂，門口泊咗架單車。似係啱啱出咗門。" },
      { id: "g-park", kind: "gate", label: "散步公園", x: 0.945, y: 0.180, target: "seaside-park" },
      { id: "g-square", kind: "gate", label: "小鎮廣場", x: 0.490, y: 0.980, target: "town-square" },
    ],
  },

  // 碼頭市集 — the parents' entrance. The船飛 is the existing parent PIN; the
  // gate itself is in the world so a child can see the place exists and be
  // told, gently, that it is for grown-ups.
  "wharf-market": {
    id: "wharf-market",
    name: "碼頭市集",
    day: "/assets/world/wharf-market-day.webp",
    night: "/assets/world/wharf-market-night.webp",
    mask: "wharf-market",
    parentsOnly: true,
    spawn: { x: 0.470, y: 0.880 },
    // Read off the shipped painting: a compass plaza with a stall on each
    // side. Which stall is which comes from what is drawn on it — maps and
    // card racks on the left, a striped market awning in the middle, the
    // harbour-master's clock-and-wheel office on the right, a notice board
    // beside it, and a quiet table under a parasol at the bottom.
    hotspots: [
      { id: "s-card", kind: "stall", label: "管理自我介紹卡", x: 0.170, y: 0.545, target: "card-desk" },
      { id: "s-new-child", kind: "stall", label: "新增孩子檔案", x: 0.435, y: 0.510, target: "new-child" },
      { id: "s-security", kind: "stall", label: "保安", x: 0.760, y: 0.545, target: "security" },
      { id: "s-lost", kind: "stall", label: "認領失物區", x: 0.880, y: 0.640, target: "lost" },
      { id: "s-pay", kind: "stall", label: "付款訂閱", x: 0.830, y: 0.815, target: "harbour" },
      { id: "g-centre", kind: "gate", label: "小鎮中心", x: 0.470, y: 0.980, target: "town-centre" },
    ],
  },
};

export const START_ZONE = "town-centre";


/** Interior art, used by the page a door leads into. */
export const ROOM_ART: Record<string, string> = {
  "cafe": "/assets/world/cafe.webp",
  "studio": "/assets/world/studio.webp",
  "album-hall": "/assets/world/album-hall.webp",
  "album-books": "/assets/world/album-books.webp",
  "fragment-room": "/assets/world/fragment-room.webp",
  "library": "/assets/world/library.webp",
  "cinema-lobby": "/assets/world/cinema-lobby.webp",
  "cinema-hall": "/assets/world/cinema-hall.webp",
  "cinema-hall-2": "/assets/world/cinema-hall-2.webp",
  "my-home": "/assets/world/my-home.webp",
};

/**
 * Rooms reached from inside another room rather than from a zone: the
 * 珍藏館's two wings, and the 戲院 behind its lobby. Each says which room it
 * came from so the return door knows where to send the child back to, which
 * is the whole of Em's "原位入口原位出口" rule for interiors.
 */
export const ROOM_DOORS: Record<string, Array<{ id: string; label: string; target: string; side: "left" | "right" }>> = {
  "album-hall": [
    { id: "r-books", label: "卡冊展示室", target: "album-books", side: "right" },
    { id: "r-fragments", label: "碎片拼合室", target: "fragment-room", side: "left" },
  ],
  "studio": [
    { id: "r-library", label: "圖書館", target: "library", side: "right" },
    { id: "r-cinema", label: "戲院大堂", target: "cinema-lobby", side: "left" },
  ],
  "cinema-lobby": [
    { id: "r-hall", label: "1 號廳", target: "cinema-hall", side: "right" },
    { id: "r-hall-2", label: "2 號廳", target: "cinema-hall-2", side: "right" },
  ],
};

/** The room a return door leads back to, derived from ROOM_DOORS. */
export const ROOM_PARENT: Record<string, string> = Object.fromEntries(
  Object.entries(ROOM_DOORS).flatMap(([parent, doors]) =>
    doors.map(door => [door.target, parent])),
);

/** Which zone a room lives in, so a deep link can put the child back outside it. */
export const ROOM_ZONE: Record<string, string> = Object.fromEntries(
  Object.values(ZONES).flatMap(zone =>
    zone.hotspots.filter(spot => spot.kind === "door").map(spot => [spot.target, zone.id])),
);

/**
 * Which half of the day it is. The world follows the child's own clock rather
 * than a setting, so evening play looks like evening.
 */
export function isDaytime(now: Date = new Date()): boolean {
  const hour = now.getHours();
  return hour >= 6 && hour < 18;
}

/**
 * Dawn, for the one zone that has art for it. A narrow window on purpose:
 * 小屋區入口 is where the child's own house is, so catching it at first light
 * should feel like catching it, not like a third of the day.
 */
export function isDawn(now: Date = new Date()): boolean {
  const hour = now.getHours();
  return hour >= 5 && hour < 7;
}

export function zoneBackground(zone: Zone, now?: Date, wide = false): string {
  // Dawn has one cut only — it is a 90-minute window, and a second painting
  // of it would be a lot of drawing for very few minutes.
  if (zone.dawn && isDawn(now)) return zone.dawn;
  if (isDaytime(now)) return (wide && zone.dayWide) || zone.day;
  return (wide && zone.nightWide) || zone.night;
}

/** A screen wider than it is tall wants the landscape painting. */
export function prefersWide(width: number, height: number): boolean {
  return width > height;
}

/**
 * The background as CSS layers: the wide cut on top, the portrait one under
 * it.
 *
 * The wide cuts are drawn per scene and arrive one scene at a time, so a zone
 * can name a `_wide` file months before that file exists. Stacking rather
 * than choosing means a missing wide cut shows the portrait painting instead
 * of showing nothing — a child on a laptop gets a slightly cropped town, not
 * a blank screen.
 */
export function zoneBackgroundLayers(zone: Zone, now?: Date, wide = false): string[] {
  const top = zoneBackground(zone, now, wide);
  const base = zoneBackground(zone, now, false);
  return top === base ? [top] : [top, base];
}

// ---------------------------------------------------------------------------
// Walkability
// ---------------------------------------------------------------------------

const decoded = new Map<string, Uint8Array>();

function bitsFor(mask: WalkMask): Uint8Array {
  const cached = decoded.get(mask.bits);
  if (cached) return cached;
  const binary = atob(mask.bits);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  decoded.set(mask.bits, bytes);
  return bytes;
}

export function maskFor(zone: Zone): WalkMask | null {
  return WALK_MASKS[zone.mask] ?? null;
}

/** Aspect ratio of a zone's map, needed to size the scrolling canvas. */
export function zoneAspect(zone: Zone): number {
  const mask = maskFor(zone);
  return mask ? mask.imageWidth / mask.imageHeight : 941 / 1672;
}

export function isWalkable(zone: Zone, x: number, y: number): boolean {
  const mask = maskFor(zone);
  if (!mask) return true;
  if (x < 0 || y < 0 || x > 1 || y > 1) return false;
  const cx = Math.min(mask.width - 1, Math.floor(x * mask.width));
  const cy = Math.min(mask.height - 1, Math.floor(y * mask.height));
  const index = cy * mask.width + cx;
  return ((bitsFor(mask)[index >> 3] >> (index & 7)) & 1) === 1;
}

/**
 * Nearest walkable point to an arbitrary one. Tapping a rooftop should walk
 * the child to the doorstep in front of it rather than doing nothing, which
 * is the difference between a world that feels responsive and one that feels
 * broken.
 */
export function nearestWalkable(zone: Zone, x: number, y: number): { x: number; y: number } | null {
  if (isWalkable(zone, x, y)) return { x, y };
  const mask = maskFor(zone);
  if (!mask) return { x, y };
  const bytes = bitsFor(mask);
  let best: { x: number; y: number } | null = null;
  let bestDistance = Infinity;
  for (let cy = 0; cy < mask.height; cy++) {
    for (let cx = 0; cx < mask.width; cx++) {
      const index = cy * mask.width + cx;
      if (((bytes[index >> 3] >> (index & 7)) & 1) === 0) continue;
      const nx = (cx + 0.5) / mask.width;
      const ny = (cy + 0.5) / mask.height;
      const distance = Math.hypot(nx - x, ny - y);
      if (distance < bestDistance) { bestDistance = distance; best = { x: nx, y: ny }; }
    }
  }
  return best;
}

/**
 * Where the child stands on arriving from somewhere specific — the gate they
 * came through, or the door of the room they just left.
 *
 * Arriving always used the zone's fixed spawn, so walking to the 碼頭 and back
 * dropped the child at the town's roundabout instead of at the 碼頭 gate they
 * had just stepped out of. A world loses its shape fast if leaving a place
 * does not put you back outside it.
 *
 * The landing point is nudged away from the entrance so its own prompt is not
 * already under the child's thumb, which would send them straight back.
 */
export function arrivalPoint(zone: Zone, from?: { zone?: string; room?: string } | null): { x: number; y: number } {
  const entrance = from?.room
    ? zone.hotspots.find(spot => spot.kind === "door" && spot.target === from.room)
    : from?.zone
      ? zone.hotspots.find(spot => spot.kind === "gate" && spot.target === from.zone)
      : null;
  if (!entrance) return zone.spawn;
  return stepAwayFrom(zone, entrance, zone.spawn);
}

/**
 * The closest walkable spot that is out of `at`'s own reach, preferring ones
 * on the `toward` side of it.
 *
 * A straight line toward the middle of the map was the obvious approach and
 * the wrong one: several entrances sit at the mouth of a narrow path, so the
 * line left walkable ground on its first step and the child never got clear
 * of the prompt. Searching the mask always finds standing room if any exists.
 */
function stepAwayFrom(zone: Zone, at: { x: number; y: number }, toward: { x: number; y: number }): { x: number; y: number } {
  const mask = maskFor(zone);
  if (!mask) return at;
  const bytes = bitsFor(mask);
  const clear = REACH * 1.7;
  let best: { x: number; y: number } | null = null;
  let bestCost = Infinity;
  for (let cy = 0; cy < mask.height; cy++) {
    for (let cx = 0; cx < mask.width; cx++) {
      const index = cy * mask.width + cx;
      if (((bytes[index >> 3] >> (index & 7)) & 1) === 0) continue;
      const nx = (cx + 0.5) / mask.width;
      const ny = (cy + 0.5) / mask.height;
      // Measured the same way hotspotNear measures, or the child could land
      // just inside the prompt they were meant to step out of.
      if (Math.hypot(nx - at.x, (ny - at.y) * 0.6) <= clear) continue;
      const away = Math.hypot(nx - at.x, ny - at.y);
      const inward = Math.hypot(nx - toward.x, ny - toward.y);
      // Close to the entrance, and on the side facing the rest of the map.
      const cost = away + inward * 0.25;
      if (cost < bestCost) { bestCost = cost; best = { x: nx, y: ny }; }
    }
  }
  return best ?? at;
}

/** Close enough to a hotspot for its prompt to appear. */
export const REACH = 0.055;

export function hotspotNear(zone: Zone, x: number, y: number): Hotspot | null {
  let best: Hotspot | null = null;
  let bestDistance = REACH;
  for (const spot of zone.hotspots) {
    // The maps are tall, so a plain distance would let the child trigger a
    // door from much further up or down the street than sideways.
    const distance = Math.hypot(spot.x - x, (spot.y - y) * 0.6);
    if (distance < bestDistance) { best = spot; bestDistance = distance; }
  }
  return best;
}
